# Site settings
title: 尘絮缘
motto: Pengfei Zhang's Blog, Keep calm and HODOR HODOR HODOR!
email: eaglezpf@sjtu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://holysparky.github.io" # the base hostname & protocol for your site
twitter_username: eaglezpf
github_username: holysparky

# Build settings
markdown: kramdown

# Customized tags
permalink: /:year/:month/:title
